apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::457480301542:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-S28VBLX7PIZU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::457480301542:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-21T13:14:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1689"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 77c5e609-38da-41f9-a0f1-3a761e48d4d8
